def language_code_converter(input_code):
    # Define a dictionary to map language codes for conversion
    if len(input_code) ==3:
        language_converter(input_code)
    else:
        code_mapping = {
    "en": "English",
    "hi": "Hindi",
    "es": "Spanish",
    "fr": "French",
    "de": "German",
    "it": "Italian",
    "pt": "Portuguese",
    "ru": "Russian",
    "ja": "Japanese",
    "ko": "Korean",
    "zh": "Chinese",
    "ar": "Arabic",
    "tr": "Turkish",
    "nl": "Dutch",
    "sv": "Swedish",
    "no": "Norwegian",
    "fi": "Finnish",
    "da": "Danish",
    "pl": "Polish",
    "cs": "Czech",
    "el": "Greek",
    "hu": "Hungarian",
    "ro": "Romanian",
    "sk": "Slovak",
    "uk": "Ukrainian",
    "he": "Hebrew",
    "th": "Thai",
    "ms": "Malay",
    "id": "Indonesian",
    "vi": "Vietnamese",
    "bg": "Bulgarian",
    "hr": "Croatian",
    "lt": "Lithuanian",
    "sl": "Slovenian",
    "et": "Estonian",
    "lv": "Latvian",
    "fa": "Persian",
    "bn": "Bengali",
    "ta": "Tamil",
    "te": "Telugu",
    "mr": "Marathi",
    "ur": "Urdu",
    "gu": "Gujarati",
    "kn": "Kannada",
    "ml": "Malayalam",
    "pa": "Punjabi",
    "or": "Odia",
    "sw": "Swahili",
    "af": "Afrikaans",
    "sq": "Albanian",
    "hy": "Armenian",
    "eu": "Basque",
    "bs": "Bosnian",
    "ca": "Catalan",
    "ceb": "Cebuano",
    "co": "Corsican",
    # Add more language codes and names as needed
}

        try:
           return code_mapping.get(input_code)
        except:
           return input_code
    
def language_converter(input_code):
    # Define a dictionary to map language codes for conversion
        code_mapping = {
    "tel": "Telugu",
    "eng": "English",
    "hin": "Hindi",
    "spa": "Spanish",
    "fra": "French",
    "ger": "German",
    "ita": "Italian",
    "por": "Portuguese",
    "rus": "Russian",
    "jpn": "Japanese",
    "kor": "Korean",
    "zho": "Chinese",
    "ara": "Arabic",
    "tur": "Turkish",
    "nld": "Dutch",
    "swe": "Swedish",
    "nor": "Norwegian",
    "fin": "Finnish",
    "dan": "Danish",
    "pol": "Polish",
    "ces": "Czech",
    "ell": "Greek",
    "hun": "Hungarian",
    "ron": "Romanian",
    "slk": "Slovak",
    "ukr": "Ukrainian",
    "heb": "Hebrew",
    "tha": "Thai",
    "msa": "Malay",
    "ind": "Indonesian",
    "vie": "Vietnamese",
    "bul": "Bulgarian",
    "hrv": "Croatian",
    "lit": "Lithuanian",
    "slv": "Slovenian",
    "est": "Estonian",
    "lav": "Latvian",
    "fas": "Persian",
    "ben": "Bengali",
    "tam": "Tamil",
    "mar": "Marathi",
    "urd": "Urdu",
    "guj": "Gujarati",
    "kan": "Kannada",
    "mal": "Malayalam",
    "pan": "Punjabi",
    "ori": "Odia",
    "swa": "Swahili",
    "afr": "Afrikaans",
    "sqi": "Albanian",
    "hye": "Armenian",
    "eus": "Basque",
    "bos": "Bosnian",
    "cat": "Catalan",
    "ceb": "Cebuano",
    "cos": "Corsican",
    "und":"Undefined"
    # Add more ISO 639-2 codes and language names as needed
}

        try:
           return code_mapping.get(input_code)
        except:
           return input_code